version: "3.8"

services:
  db:
    image: mysql:8.0.31
    volumes:
      - sqldata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=game
      - MYSQL_USER=postgres
      - MYSQL_ROOT_PASSWORD=postgres
      - MYSQL_PASSWORD=postgres

volumes:
  sqldata:
